# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cea8ef79dcd195c14a950f8d1bb2667dc928f97c3602bd1256c1d8a124726ed72d39c050f166a1953ae3ddc485caff9d053efd5d3dca030ed98badc75e525727

test:
  secret_key_base: 0c0976b0df2f7623a7b79b2deb9ab2465b722a3e96ad8af14f56fbcd5d6f62bc0567c98be0486d1f576cb279933ddfa938b56250052ad2e8a88d3c71cd990848

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
